### PR TITLE
Added initial support for 5" turing screen

### PR DESCRIPTION
**Pull request by ErikApption**
Based on https://github.com/mathoudebine/turing-smart-screen-python/blob/main/library/lcd/lcd_comm_rev_c.py
- Supports full image display
- Partial image update but this seems to have limited support. Example 1 doesn't work with this.
- Added unit tests to compare python output with c# code

### CODE REVIEW

**Comment by usausa** [comment]
@ErikApption 
Thanks for the pull request.
I would like to merge, but I would like you to do the following.

* Make sure there are no warnings when doing a Release build.
* The name should match the Python source, not 5inch.
* Delete unnecessary files such as backup and make a pull request with minimal content.

**Comment by ErikApption** [comment]
Hi @usausa, I believe I fixed all the issues you asked.

**Comment by usausa** [comment]
@ErikApption
There is a build warning, so please check it.  
This project uses static checking by Analyzer as a coding rule.  
There is an AnalysisMode setting in Directory.Build.props, and if you build in Release mode, the following warning will be output, so I would like you to take action.

```
1>D:\GitHub\turing-smart-screen\TuringSmartScreenLib\TuringSmartScreenBufferC.cs(11,47,11,58): warning CA1825: 不要な長さ 0 の配列の割り当てを避けます。代わりに Array.Empty<byte>() を使用してください。 (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1825)
...
```

**Comment by ErikApption** [comment]
I missed the release configuration... I think I cleaned the remaining issues

**Pull request merged**
